"""Minimal Bitcoin Core JSON-RPC client for blockchain inspection."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['BitcoinRPC']

# %% ../nbs/00_core.ipynb #cc663414-296d-49c0-bc95-896c3d3e3d23
import httpx
from pathlib import Path
from typing import Any

# %% ../nbs/00_core.ipynb #3f052007
class BitcoinRPC:
    "Tiny synchronous JSON-RPC client for Bitcoin Core."
    def __init__(
        self,
        url: str | None = None, # Where to reach bitcoind e.g. 127.0.0.1:8332
        auth: tuple[str, str] | None = None, # Auth cookie or username+password
        timeout: float = 30.0,
    ):
        self.url, auth, timeout = url, auth, timeout
        self._client = httpx.Client(base_url=url, auth=auth, timeout=timeout)
        self._id = 0

    def call(self, method: str, *params: Any) -> Any:
        "Invoke a Bitcoin Core RPC `method` with positional `params`."
        self._id += 1
        r = self._client.post(
            "/",
            json={
                "jsonrpc": "2.0",
                "id": self._id,
                "method": method,
                "params": list(params),
            },
        )
        r.raise_for_status()
        body = r.json()
        if body.get("error"):
            raise RuntimeError(body["error"])
        return body["result"]

    def close(self):
        self._client.close()

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        self.close()
