# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_db.ipynb.

# %% auto #0
__all__ = ['SCHEMA_SQL', 'create_schema', 'insert_block', 'insert_transaction_rows', 'block_fee_buckets']

# %% ../nbs/03_db.ipynb #7be407ee-67ee-499d-b8c1-e6ed37df002d
import psycopg
from psycopg.rows import dict_row

# %% ../nbs/03_db.ipynb #6448e671-b5d0-4726-be41-d8da47c90ea5
SCHEMA_SQL = """
create table if not exists dim_block (
    block_key bigserial primary key,
    block_hash text not null unique,
    height integer not null,
    block_time_utc timestamptz not null
);

create table if not exists fact_transaction (
    transaction_key bigserial primary key,
    block_key bigint not null references dim_block(block_key),
    txid text not null,
    wtxid text,
    position_in_block integer not null,
    version integer,
    locktime bigint,
    size_bytes integer,
    vsize_vb integer not null,
    weight_wu integer,
    input_count integer not null,
    output_count integer not null,
    input_value_sats bigint,
    output_value_sats bigint not null,
    fee_sats bigint,
    fee_sat_vb numeric,
    is_coinbase boolean not null,
    has_witness boolean not null,

    unique (block_key, position_in_block),
    unique (block_key, txid)
);

create index if not exists dim_block_height_idx
    on dim_block (height);

create index if not exists fact_transaction_block_fee_idx
    on fact_transaction (block_key, is_coinbase, fee_sat_vb);
"""

# %% ../nbs/03_db.ipynb #b18b112d-5b21-4928-bfb6-a2faaab7acb8
def create_schema(conn) -> None:
    "Create the minimum warehouse tables for block fee analytics."
    with conn.cursor() as cur:
        cur.execute(SCHEMA_SQL)
    conn.commit()

# %% ../nbs/03_db.ipynb #bf1e9819-21e3-48ad-bf4d-d2f3a4c2d16a
def insert_block(conn, block: dict) -> int:
    "Insert a block dimension row and return its block_key."
    with conn.cursor() as cur:
        cur.execute(
            """
            insert into dim_block (
                block_hash,
                height,
                block_time_utc
            )
            values (
                %(block_hash)s,
                %(height)s,
                to_timestamp(%(time)s)
            )
            on conflict (block_hash)
            do update set
                height = excluded.height,
                block_time_utc = excluded.block_time_utc
            returning block_key;
            """,
            {
                "block_hash": block["hash"],
                "height": block["height"],
                "time": block["time"],
            },
        )
        row = cur.fetchone()

    if row is None:
        raise RuntimeError("insert_block did not return a block_key")

    conn.commit()
    return row["block_key"]

# %% ../nbs/03_db.ipynb #4dab159b-15e0-46b5-8075-5910aa5ae377
def insert_transaction_rows(conn, block_key: int, rows: list[dict]) -> None:
    "Insert transaction fee-analysis rows for one block."
    tx_rows = [{**row, "block_key": block_key} for row in rows]
    if not tx_rows:
        return

    with conn.cursor() as cur:
        cur.executemany(
            """
            insert into fact_transaction (
                block_key,
                txid,
                wtxid,
                position_in_block,
                version,
                locktime,
                size_bytes,
                vsize_vb,
                weight_wu,
                input_count,
                output_count,
                input_value_sats,
                output_value_sats,
                fee_sats,
                fee_sat_vb,
                is_coinbase,
                has_witness
            )
            values (
                %(block_key)s,
                %(txid)s,
                %(wtxid)s,
                %(position_in_block)s,
                %(version)s,
                %(locktime)s,
                %(size_bytes)s,
                %(vsize_vb)s,
                %(weight_wu)s,
                %(input_count)s,
                %(output_count)s,
                %(input_value_sats)s,
                %(output_value_sats)s,
                %(fee_sats)s,
                %(fee_sat_vb)s,
                %(is_coinbase)s,
                %(has_witness)s
            )
            on conflict (block_key, txid)
            do update set
                wtxid = excluded.wtxid,
                position_in_block = excluded.position_in_block,
                version = excluded.version,
                locktime = excluded.locktime,
                size_bytes = excluded.size_bytes,
                vsize_vb = excluded.vsize_vb,
                weight_wu = excluded.weight_wu,
                input_count = excluded.input_count,
                output_count = excluded.output_count,
                input_value_sats = excluded.input_value_sats,
                output_value_sats = excluded.output_value_sats,
                fee_sats = excluded.fee_sats,
                fee_sat_vb = excluded.fee_sat_vb,
                is_coinbase = excluded.is_coinbase,
                has_witness = excluded.has_witness;
            """,
            tx_rows,
        )

    conn.commit()

# %% ../nbs/03_db.ipynb #5f2323c7-9f25-4bbf-b2bc-0f6e9d6148f16
def block_fee_buckets(conn, block_key: int, max_bucket: int = 200) -> list[dict]:
    "Return chart-ready fee-rate buckets for one block."
    with conn.cursor() as cur:
        cur.execute(
            """
            select
                least(floor(fee_sat_vb)::int, %(max_bucket)s) as bucket_lower_sat_vb,
                case
                    when floor(fee_sat_vb)::int >= %(max_bucket)s then null
                    else floor(fee_sat_vb)::int + 1
                end as bucket_upper_sat_vb,
                count(*) as tx_count,
                sum(vsize_vb) as total_vsize_vb,
                sum(fee_sats) as total_fees_sats,
                sum(fee_sats)::numeric / nullif(sum(vsize_vb), 0) as mean_fee_sat_vb
            from fact_transaction
            where block_key = %(block_key)s
              and is_coinbase = false
              and fee_sat_vb is not null
            group by 1, 2
            order by 1;
            """,
            {"block_key": block_key, "max_bucket": max_bucket},
        )
        return cur.fetchall()
