# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_db.ipynb.

# %% auto #0
__all__ = ['SCHEMA_SQL', 'create_schema', 'insert_block']

# %% ../nbs/04_db.ipynb #7be407ee-67ee-499d-b8c1-e6ed37df002d
import psycopg
from psycopg.rows import dict_row

# %% ../nbs/04_db.ipynb #6448e671-b5d0-4726-be41-d8da47c90ea5
SCHEMA_SQL = """
create table if not exists dim_block (
    block_key bigserial primary key,
    block_hash text not null unique,
    height integer not null,
    block_time_utc timestamptz not null
);

create table if not exists fact_transaction (
    transaction_key bigserial primary key,
    block_key bigint not null references dim_block(block_key),
    txid text not null,
    wtxid text,
    position_in_block integer not null,
    version integer,
    locktime bigint,
    size_bytes integer,
    vsize_vb integer not null,
    weight_wu integer,
    input_count integer not null,
    output_count integer not null,
    input_value_sats bigint,
    output_value_sats bigint not null,
    fee_sats bigint,
    fee_sat_vb numeric,
    is_coinbase boolean not null,
    has_witness boolean not null,

    unique (block_key, position_in_block),
    unique (block_key, txid)
);
"""

# %% ../nbs/04_db.ipynb #b18b112d-5b21-4928-bfb6-a2faaab7acb8
def create_schema(conn) -> None:
    "Create the minimum warehouse tables for block fee analytics."
    with conn.cursor() as cur:
        cur.execute(SCHEMA_SQL)
    conn.commit()

# %% ../nbs/04_db.ipynb #bf1e9819-21e3-48ad-bf4d-d2f3a4c2d16a
def insert_block(conn, block: dict) -> int:
    "Insert a block dimension row and return it's block_key."
    with conn.cursor() as cur:
        cur.execute(
            """
            insert into dim_block (
                block_hash,
                height,
                block_time_utc
            )
            values (
                %(block_hash)s,
                %(height)s,
                to_timestamp(%(time)s)
            )
            on conflict (block_hash)
            do update set
                height = excluded.height,
                block_time_utc = excluded.block_time_utc
            returning block_key;
            """,
            {
                "block_hash": block["hash"],
                "height": block["height"],
                "time": block["time"]
            },
        )
        row = cur.fetchone()

    conn.commit()
    return row["block_key"]
