# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_transform.ipynb.

# %% auto #0
__all__ = ['SATS_PER_BTC', 'btc_to_sats', 'is_coinbase_tx', 'block_fee_rows']

# %% ../nbs/03_transform.ipynb #6bf8f93c-e5fe-4138-8cd9-4dbacd32f4fd
from decimal import Decimal

# %% ../nbs/03_transform.ipynb #6dc407af-b841-4256-b41b-3f216f191023
SATS_PER_BTC = Decimal("100000000")

# %% ../nbs/03_transform.ipynb #a73becfc-ec14-4c5d-a20b-0546fb7c1456
def btc_to_sats(value) -> int:
    "Convert a Bitcoin Core BTC value to satoshis."
    return int((Decimal(str(value)) * SATS_PER_BTC).to_integral_exact())

# %% ../nbs/03_transform.ipynb #13899d4d-9d82-4ce8-97b5-914201e33b5e
def is_coinbase_tx(tx: dict) -> bool:
    "Return True if `tx` is a coinbase transaction."
    return len(tx.get("vin", [])) == 1 and "coinbase" in tx["vin"][0]

# %% ../nbs/03_transform.ipynb #9c878bc6-4774-4730-b562-96f6288f3c53
def block_fee_rows(block: dict) -> list[dict]:
    "Return one fee-analysis row per transaction in a verbosity=3 block."
    rows = []

    for i, tx in enumerate(block["tx"]):
        is_coinbase = is_coinbase_tx(tx)

        if is_coinbase:
            input_sats = None
            output_sats = sum(btc_to_sats(vout["value"]) for vout in tx["vout"])
            fee_sats = None
            fee_sat_vb = None
        else:
            try:
                input_sats = sum(
                    btc_to_sats(vin["prevout"]["value"])
                    for vin in tx["vin"]
                )
            except KeyError as exc:
                raise ValueError(
                    "block_fee_rows requires getblock verbosity=3 so vin prevouts are present"
                ) from exc
            output_sats = sum(btc_to_sats(vout["value"]) for vout in tx["vout"])
            fee_sats = input_sats - output_sats
            fee_sat_vb = fee_sats / tx["vsize"]

        rows.append({
            "txid": tx["txid"],
            "wtxid": tx.get("hash"),
            "position_in_block": i,
            "version": tx.get("version"),
            "locktime": tx.get("locktime"),
            "size_bytes": tx.get("size"),
            "vsize_vb": tx["vsize"],
            "weight_wu": tx.get("weight"),
            "input_count": len(tx.get("vin", [])),
            "output_count": len(tx.get("vout", [])),
            "input_value_sats": input_sats,
            "output_value_sats": output_sats,
            "fee_sats": fee_sats,
            "fee_sat_vb": fee_sat_vb,
            "is_coinbase": is_coinbase,
            "has_witness": "hash" in tx and tx["hash"] != tx["txid"],
        })

    return rows
